export const instantApps = [
  {
    id: "ffd0e59cc2b34871b59c060ffb9c5d8f",
    owner: "App_Gal",
    created: 1642607312000,
    modified: 1646320783000,
    guid: null,
    name: null,
    title: "Refugee Resettlement",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3'>The office of the <a href='https://www.unhcr.org/en-us/' style='color:rgb(83, 181, 238);' target='_blank' rel='nofollow ugc noopener noreferrer'>United Nations High Commissioner for Refugees</a> (UNHCR), created as an aftermath of the Second World War, safeguards the rights and well-being of people who are forced to flee their countries. '<i><strong>Resettlement</strong></i>' is a solution offered by UNHCR to help refugees who cannot return to their home countries because of war, conflict or persecution.</font></p><p style='color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3'>UNHCR defines resettlement as &quot;<span style='color:rgb(34, 34, 34);'><i>the transfer of refugees from an asylum country to another State, that has agreed to admit them and ultimately grant them permanent residence</i>&quot;.</span></font></p><p style='color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3'>Using information extracted from the UNHCR website, this app shows the flow of refugees in the years 2020 and 2021.</font></p>",
    tags: ["Instant Apps", "sidebar", "refugee", "resettlement", "flow-map"],
    snippet:
      "Where did refugees come from and where did they go in the years 2020 and 2021?\nExplore this app to know more!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/ffd0e59cc2b34871b59c060ffb9c5d8f/info/thumbnail/thumbnail1646320781513.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/sidebar/index.html?appid=a66bf857a12c4b14a6ca8a22dd7ed49b",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 407,
    groupCategories: [
      "/Categories/Industries/Health and Human Services/Humanitarian Services",
      "/Categories/Industries/Global and Regional",
      "/Categories/Templates/Sidebar"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678078800000
  },
  {
    id: "17b6f2023e034966b2bf04ec1b802a72",
    owner: "App_Gal",
    created: 1645802644000,
    modified: 1645803526000,
    guid: null,
    name: null,
    title: "Global Dams and Water Stress",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;sans-serif&quot;;'><font color='#404040' size='3' style='background-color:rgb(255, 255, 255);'>Building dams is often the most common response to water shortages and droughts across the globe.  The goal is to store water during wet periods and then release it during dry periods in order to stabilize water availability. </font></p><p style='font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;sans-serif&quot;;'><font color='#404040' size='3' style='background-color:rgb(255, 255, 255);'>As the human population grows and the climate changes, the issue of water shortage keeps growing. In several nations dams are being built nowadays for reasons other than improving water supplies, giving rise to a lot of heated debate globally. </font></p><p style='font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;sans-serif&quot;;'><font color='#404040' size='3' style='background-color:rgb(255, 255, 255);'>While one half of the population believes that dams improve water shortages, the other argues that they can paradoxically contribute to worsening the shortage. Explore the app to learn more about dams across the globe, their primary uses and water stress.</font></p><p style='color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;sans-serif&quot;; font-size:14px;'><span style='color:rgb(51, 51, 51);'>Data Sources: GRanD, Global Dam Watch; FAO Database</span></p>",
    tags: ["Instant Apps", "Interactive-Legend", "Dams", "Water-Stress", "Water-Shortage"],
    snippet: "Explore the app to learn more about dams across the globe, their primary uses and water stress.",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/17b6f2023e034966b2bf04ec1b802a72/info/thumbnail/thumbnail1645803524049.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/interactivelegend/index.html?appid=e860eac674ac46378cacc497915b7de2",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 370,
    groupCategories: [
      "/Categories/Templates/Interactive Legend",
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Global and Regional",
      "/Categories/Industries/Environment and Natural Resources/Natural Resources"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678082400000
  },
  {
    id: "0e73b229bb8741b48b659596b4b740b2",
    owner: "App_Gal",
    created: 1648749051000,
    modified: 1648749633000,
    guid: null,
    name: null,
    title: "Sidewalk Cafes of New York City",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='margin-top:0px; margin-bottom:0in; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><span style='font-family:Verdana, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><font color='#000000' size='3' style='font-family:inherit;'>The restaurant industry is an essential component of New York City's socioeconomic fabric. The concept of a sidewalk café is relatively new to the industry and gained traction only in the mid-60's when city officials started encouraging street dining - particularly in Greenwich Village. Currently, sidewalk cafes are regarded as neighborhood amenities that increase vitality and encourage social interactions. Additionally, since sidewalks represent a huge fraction of the city's public spaces, the idea of sidewalk cafes and outdoor sitting is highly valued by urban planners.</font></span></p><p style='margin-top:0px; margin-bottom:0in; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>This Nearby app maps all the licensed sidewalk cafes of New York City and allows users to search for cafes closest to them. The app comes with the following functions - </font></span></p><ul><li><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>Editable minimum and maximum search distances</font></span></li><li><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>Option to export the results to a PDF document</font></span></li><li><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>Option to take a screenshot</font></span></li><li><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>Directions to the results from the user's location</font></span></li><li><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>Option to Filter based on type of café (Enclosed, Unenclosed or Small Unenclosed Cafes)</font></span></li></ul><p style='margin-top:0px; margin-bottom:0in; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><span style='font-family:Verdana, sans-serif;'><font color='#000000' size='3' style='font-family:inherit;'>Every sidewalk café includes information about its location and its type.</font></span></p><p style='margin-top:0px; margin-bottom:0in; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><span style='font-family:Verdana, sans-serif;'><font color='#000000' style='font-family:inherit;'><br /></font></span></p><p style='margin-top:0px; margin-bottom:0in; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><font color='#000000' size='2' style='font-family:inherit;'><span style='font-family:Verdana, sans-serif;'><b>Data Source:</b> </span><a href='https://data.cityofnewyork.us/Business/Sidewalk-Caf-Licenses-and-Applications/qcdj-rwhu' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>New York City Department of Consumer Affairs (March, 2022)</a></font></p>",
    tags: ["Nearby", "Instant-Apps", "Sidewalk-Cafe", "NewYorkCity", "NYC"],
    snippet: "Search for your closest sidewalk café in New York City!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/0e73b229bb8741b48b659596b4b740b2/info/thumbnail/thumbnail1648749632062.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: "New York City Department of Consumer Affairs (March, 2022)",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/nearby/index.html?appid=f703510c40cc47fab744accb847ea75a",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 342,
    groupCategories: ["/Categories/Industries/Retail", "/Categories/Templates/Nearby"],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678082400000
  },
  {
    id: "b5423bcf93814b1a93e1992b450b08c3",
    owner: "App_Gal",
    created: 1646858293000,
    modified: 1646862371000,
    guid: null,
    name: null,
    title: "Improvement to Land Ratio - Gateway Cities of Greater Boston",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<h3 style='font-weight:400; margin:0px 0px 0.75rem; font-size:1.69949rem; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif;'><span style='font-family:inherit;'><font size='3' style='font-family:inherit;'>Explore the Improvement to Land Ratio in the Gateway Cities of Greater Boston, mapped using data from MAPC Boston's open data site. The cities included in the app are - Chelsea, Everett, Lynn, Malden, Peabody, Quincy, Revere and Salem.</font></span></h3><p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>The Improvement Ratio is an interesting way to look at a city as it immediately reveals land parcels that are under-utilized. It is calculated as a ratio between value of all improvements built upon a land parcel to the value of the land contained within the parcel boundaries. </font></p><p style='margin-top:0px; margin-bottom:1.5rem; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size:14px;'> </p><p style='margin-top:0px; margin-bottom:1.5rem; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size:14px;'><strong>Data Source: </strong><a href='https://datacommon.mapc.org/browser/datasets/360' style='color:rgb(83, 181, 238); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>DataCommon, MAPC Boston</a></p>",
    tags: [
      "Instant Apps",
      "sidebar",
      "land-parcels",
      "boston",
      "gateway-cities",
      "massachusetts",
      "improvement-ratio",
      "real-estate"
    ],
    snippet: "Explore the Improvement to Land Ratio in the Gateway Cities of Greater Boston.",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/b5423bcf93814b1a93e1992b450b08c3/info/thumbnail/thumbnail1646859409498.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/sidebar/index.html?appid=f37da8e6c2cc4285bcd5c17b05eb9eb5",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 360,
    groupCategories: [
      "/Categories/Industries/Public Works",
      "/Categories/Industries/Real Estate",
      "/Categories/Templates/Sidebar"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678060800000
  },
  {
    id: "e75a2e13976747a3844b937d6481bcd1",
    owner: "App_Gal",
    created: 1657310905000,
    modified: 1657311024000,
    guid: null,
    name: null,
    title: "Global Youth Literacy",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='margin:revert; font-size:16px; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>Sustainable Development Goal 4 stresses on ensuring &quot;inclusive and equitable quality education&quot; and promoting &quot;lifelong learning opportunities for all&quot;. Literacy has been on the agenda for sustainable development for almost over two decades and still in 2016, 750 million adults (above 15 years) around the world were illiterate, two-thirds of which were women. 102 million of the illiterate population comprised of the youth (15-24 years). Gender disparity has also been persistent despite all efforts.</font></p><p style='margin:revert; font-size:16px; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>Over the last two years, most education institutions around the world faced severe unprecedented challenges due to the COVID-19 outbreak. The UN Economic and Social Council reported that 147 million children failed to attend in-person classes over the past two years. The pandemic could lead to a loss of $17 trillion in lifetime earnings in present value for this generation of children. Given the current global situation, improving education participation and bridging the gender gap has thus become even more important specifically for children from disadvantaged socio-economic backgrounds.</font></p><p style='margin:revert; font-size:16px; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>Now, let's take a look at the Gender Parity of Youth Literacy around the world and Overall Youth Literacy Rates of countries! Use the 'Layer List' icon in the bottom-right corner to toggle between the Gender Parity and Overall Youth Literacy layers.</font></p><p style='margin:revert; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:14px;'><span style='font-family:inherit; margin:revert;'><b>Source:</b></span> UNESCO Institute for Statistics and UN Sustainable Development Goals</p>",
    tags: ["Instant-Apps", "Interactive-Legend", "Education", "Gender-Gap", "Youth-Literacy", "Literacy"],
    snippet:
      "Take a look at the Gender Parity of Youth Literacy around the world and Overall Youth Literacy Rates of countries!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/e75a2e13976747a3844b937d6481bcd1/info/thumbnail/thumbnail1657310988343.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: "UNESCO Institute for Statistics",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/interactivelegend/index.html?appid=0b4fb3b721194330b63331c8ff35ea22",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 242,
    groupCategories: [
      "/Categories/Templates/Interactive Legend",
      "/Categories/Industries/Education and Research",
      "/Categories/Industries/Global and Regional"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678071600000
  },
  {
    id: "5c20337788ff4facb4ba0d16994b7da2",
    owner: "App_Gal",
    created: 1659482485000,
    modified: 1659482559000,
    guid: null,
    name: null,
    title: "The Western Expansion: Mapping the Homesteading History",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='margin:revert; font-size:16px; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; text-align:justify;'><span style='font-family:inherit; font-weight:revert; margin:revert;'><font size='3' style='font-family:inherit;'>The Homestead Act of 1862, signed by President Abraham Lincoln, is one of the most important laws passed that augmented the expansion of the Western territory with simultaneous displacement of Native Americans. The Act offered Americans an opportunity to own 160 acres of public land for a small filing fee and improve it over a span of five years. To make a claim, a homesteader had to be the head of household or 21 years of age and had to certify that they had never borne arms against the nation. The Act allowed citizens from different walks of life to own land.</font></span></p><p style='margin:revert; font-size:16px; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; text-align:justify;'><font size='3' style='font-family:inherit;'><span style='font-family:inherit; font-weight:revert; margin:revert;'>The Homestead Act remained active for more than a century and resulted in the distribution of more than 275 million acres of land (approximately 1.6 million homestead settlements). </span><i>The app visualizes the history of homesteading over time and space in 30 American states from 1868 to 1961. Use the time slider to explore the percentage of land in the state claimed by homesteaders.</i></font></p><p style='margin:revert; font-size:16px; color:rgb(64, 64, 64); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; text-align:justify;'><font size='2' style='font-family:inherit;'><span style='font-family:inherit; font-weight:revert; margin:revert;'>Data Source: </span><font style='font-family:inherit;'>Homesteading the Plains: Toward a New History</font></font></p>",
    tags: ["Instant-Apps", "Slider", "States", "United-States", "Homesteads", "Homestead-Act"],
    snippet: "Explore the history of homesteading over time and space in 30 American states from 1868 to 1961!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/5c20337788ff4facb4ba0d16994b7da2/info/thumbnail/thumbnail1659482557993.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/slider/index.html?appid=9f178aa152cd4698bad0e1b0382253a0",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 222,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Education and Research",
      "/Categories/Templates/Slider",
      "/Categories/Industries/Global and Regional"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678096800000
  },
  {
    id: "b99e1d7dd4f54a9bbd440055dbda426b",
    owner: "App_Gal",
    created: 1648651942000,
    modified: 1648652819000,
    guid: null,
    name: null,
    title: "Health Insurance Demographics of Florida",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<font color='#000000' style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>Health Insurance is a way of financing an individual's health care expenses. The American Community Survey broadly classifies health insurance into two categories for the civilian, noninstitutionalized population of the United States - public health insurance coverage and private health insurance coverage. </font><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'><font color='#000000'><br /></font></span></div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'><font color='#000000'>According to the American Community Survey (5-years, 2020), 12.67% of the noninstitutionalized civilian population of Florida does not have health insurance coverage, which is higher than the national average and makes Florida one of the top five states with a high percentage of uninsured population.</font></span><div style='font-family:inherit;'><font color='#000000'><span style='font-family:&quot;Avenir Next&quot;;'><font size='3' style='font-family:inherit;'>Explore the app to learn more about the health insurance demographics of Florida at a census tract level </font></span>mapped using American Community Survey (2020) 5-year estimate dataset. The portfolio app includes six different tabs of web maps and Instant Apps visualizing the following - </font></div><div style='font-family:inherit;'><ol><li><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'><font color='#000000'>Share of insured and uninsured population of Florida (Web Map)</font></span></li><li><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'><font color='#000000'>Distribution of insured population by age-group (<font face='inherit'>Instant App</font>)</font></span></li><li><font color='#000000'><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'>Distribution of uninsured population by age-group </span>(<font face='inherit'>Instant App</font>)</font></li><li><font color='#000000'><font size='3' style='font-family:inherit;'>Health Insurance Coverage Gender Gap among insured and uninsured population </font>(Web Map)</font></li><li><font color='#000000'><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'>Distribution of uninsured population by Disability Status, Poverty and Living Arrangements </span>(<font face='inherit'>Instant App</font>)</font></li><li><font color='#000000'><font size='3' style='font-family:inherit;'>Distribution of uninsured population by Race and Citizenship Status </font>(<font face='inherit'>Instant App</font>)</font></li></ol><span style='font-family:&quot;Avenir Next&quot;; font-size:medium;'><font color='#000000'> Every tab comes with an information icon which can be used to know more about the layer visualization and app functions. The app can be used as a resource for implementing informed reforms and changes.</font></span><br /></div></div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><span style='font-family:&quot;Avenir Next&quot;; color:rgb(74, 74, 74); font-size:medium;'><br /></span></div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><b><font size='2' style='font-family:inherit;'>Data Source:</font></b><font size='2' style='font-family:inherit;'> ACS Table S2701 (5-year estimate, 2020), <a href='https://data.census.gov/cedsci/' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>United States Census Bureau</a></font></div>",
    tags: ["Instant Apps", "Portfolio", "Health-Insurance", "Insurance", "Florida", "Census-Tracts", "Socioeconomic"],
    snippet:
      "Explore the app to learn more about the selected socioeconomic demographics of health insurance coverage of Florida at a census tract level!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/b99e1d7dd4f54a9bbd440055dbda426b/info/thumbnail/thumbnail1648652816841.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation:
      "U.S. Census Bureau's American Community Survey (ACS) 2016-2020 5-year estimates, Table(s) S2701",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/portfolio/index.html?appid=294907c5abfb480b9724d3b23e6399ca",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 336,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Insurance",
      "/Categories/Templates/Portfolio"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678060800000
  },
  {
    id: "da1bd6caedcd487db1c7100c6ff5ac4d",
    owner: "App_Gal",
    created: 1654101577000,
    modified: 1654102341000,
    guid: null,
    name: null,
    title: "Museums in United States",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<div style='font-family:&quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size:16px; margin:0px; padding:0px; clear:both; color:rgb(0, 0, 0);'><p style='margin-top:0px; margin-bottom:0px; padding:0px; font-kerning:none; background-color:transparent; color:windowtext;'><font size='4' style='font-family:inherit;'><span style='font-family:Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; margin:0px; padding:0px; font-variant-ligatures:none !important;'><span style='font-family:inherit; margin:0px; padding:0px;'>Museums have always been known for their educational and leisure value and for the contributions that they make to the tourism economy of any region. But in the current years, there has been a growing body of research that highlights the broader societal impacts of museums, particularly their potential positive impact on the social wellbeing of communities. The Institute of Museum and Library Services (IMLS), an independent federal agency that aims to support and empower America’s museums and libraries through research, grants, and policy development, in their recent studies, looks at the diverse ways in which museums promote social inclusion and wellbeing, particularly community health, economic wellbeing, and school effectiveness. Considering these studies based on museums’ engagement with several community concerns, the broader target audience of this Chart Viewer App</span><span style='font-family:inherit; margin:0px; padding:0px;'> includes researchers, journalists, practitioners, policymakers, and government agencies at all administrative levels. </span></span><span style='font-family:Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; margin:0px; padding:0px;'> </span></font></p></div><div style='font-family:&quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size:16px; margin:0px; padding:0px; clear:both; color:rgb(0, 0, 0);'><p style='margin-top:0px; margin-bottom:0px; padding:0px; font-kerning:none; background-color:transparent; color:windowtext;'><span style='font-family:Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; margin:0px; padding:0px; font-variant-ligatures:none !important;'><span style='font-family:inherit; margin:0px; padding:0px;'><font size='4' style='font-family:inherit;'><br /></font></span></span></p><p style='margin-top:0px; margin-bottom:0px; padding:0px; font-kerning:none; background-color:transparent; color:windowtext;'><span style='font-family:Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; margin:0px; padding:0px; font-variant-ligatures:none !important;'><font size='4' style='font-family:inherit;'><span style='font-family:inherit; margin:0px; padding:0px;'>The current version of this Instant App offers a generic overview of museums spread across the United States. It maps 7,000+ museums in the country and nine different bar charts that </span><span style='font-family:inherit; margin:0px; padding:0px;'>provide</span><span style='font-family:inherit; margin:0px; padding:0px;'> extra insight into the distribution of these museums by type, state, region, and revenue group. The map </span><span style='font-family:inherit; margin:0px; padding:0px;'>exhibits</span><span style='font-family:inherit; margin:0px; padding:0px;'> a clustered visualization of museums by type, including Art, History, and Science Museums, Children’s Museums, Arboretums, and Botanical Gardens. It comes with popups that </span><span style='font-family:inherit; margin:0px; padding:0px;'>provide</span><span style='font-family:inherit; margin:0px; padding:0px;'> related cluster information - the count of museums and the predominant type of museum within the cluster, and feature information, including museum address, contact, and website URL. This publicly available dataset, created by the Institute of Museum and Library Services (IMLS), is a compilation of data from various public, non-profit, and third-party sources. The app highlights the newest enhancements of the Chart Viewer Template that allows the user to display up to three charts at once alongside the map and to expand either the charts or the map to be viewed in a full-screen mode.</span></font></span></p><p style='margin-top:0px; margin-bottom:0px; font-size:12px; padding:0px; font-kerning:none; background-color:transparent; color:windowtext;'><span style='font-family:Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; margin:0px; padding:0px; font-size:12pt; font-variant-ligatures:none !important;'><br /></span></p><p style='margin-top:0px; margin-bottom:0px; font-size:12px; padding:0px; font-kerning:none; background-color:transparent; color:windowtext;'><span style='font-family:Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; margin:0px; padding:0px; font-size:12pt; font-variant-ligatures:none !important;'>Data Source: </span><a href='https://www.imls.gov/research-evaluation/data-collection/museum-data-files' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>Institute of Museum and Library Services, 2018</a></p></div>",
    tags: ["Instant-Apps", "Chartviewer", "Museums", "Bar-Chart", "United-States"],
    snippet:
      "Learn more about 7,000+ museums in the United States along with bar charts that provide extra insight into the distribution by type, state, and revenue.",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/da1bd6caedcd487db1c7100c6ff5ac4d/info/thumbnail/thumbnail1654101669896.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: "Museum Data Files, Institute of Museum and Library Services, 2018",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/charts/index.html?appid=148f5599241c4795a1ef8170a4581953",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 286,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Education and Research",
      "/Categories/Templates/Chart Viewer"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678068000000
  },
  {
    id: "502b7428eb1340a2805abfbc6f6be4b3",
    owner: "App_Gal",
    created: 1650380104000,
    modified: 1650380662000,
    guid: null,
    name: null,
    title: "Los Angeles Public Transit Information",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<span style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>Data and maps features in this app include:</span><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>- Los Angeles metro rail layers</div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>- Los Angeles Metro bus lines</div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>- Los Angeles public transit stations: Metrolink, metro, transit, amtrak, etc. </div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>- Los Angeles major highways</div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><br /></div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>Data collected using the Los Angeles GeoHub: <a href='https://geohub.lacity.org/' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>https://geohub.lacity.org/</a></div>",
    tags: ["Instant-Apps", "Portfolio", "Accordian", "Los-Angeles", "Public-Transit", "Transportation"],
    snippet:
      "Los Angeles has always been a place driven by exploration. Find resources about public transit and plans to further improve public transit in Los Angeles.",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/502b7428eb1340a2805abfbc6f6be4b3/info/thumbnail/thumbnail1650380660505.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/portfolio/index.html?appid=d84dac07082f46828d44a21f6b40c0b4",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 320,
    groupCategories: ["/Categories/Templates/Portfolio", "/Categories/Industries/Transportation"],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678096800000
  },
  {
    id: "391caae3232b48579cdaf3cf39fb3e8c",
    owner: "App_Gal",
    created: 1648130311000,
    modified: 1648130889000,
    guid: null,
    name: null,
    title: "Petroleum Facilities of Texas - Toxic Release and Waste Management",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<h3 style='font-family:&quot;Avenir Next&quot;;'><font color='#000000' size='3' style='background-color:rgb(255, 255, 255); font-weight:normal;'>In 2020, the petroleum facilities of Texas (NAICS 324) accounted for the highest amount of petroleum-based toxic releases in the US. </font></h3><p style='font-family:&quot;Avenir Next&quot;;'><font color='#000000' size='3' style='background-color:rgb(255, 255, 255);'>This app maps all the petroleum facilities of Texas, along with related information about waste management. The information can be used as a resource for supporting environment-based decision-making by communities and public and private agencies.</font></p><p style='font-family:&quot;Avenir Next&quot;;'><font color='#000000' size='3' style='background-color:rgb(255, 255, 255);'>Start exploring the data in this app by using the countdown section to page through the top 10 facilities with highest amount of toxic releases in 2020. While paging through the locations in the countdown section, the map will focus on the extent that showcases that feature. The Leaderboard ranks the top 10 facilities that recycled or treated their petroleum toxic releases in 2020.</font></p><p style='font-family:&quot;Avenir Next&quot;;'><span style='background-color:rgb(255, 255, 255);'><font size='2'><font color='#000000'><b>Data Source:</b> </font><span style='box-sizing:inherit; font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color:rgb(24, 33, 43);'><span style='box-sizing:inherit;'>United States Environmental Protection Agency. (2022). </span><i><span style='box-sizing:inherit;'>TRI Explorer</span></i><span style='box-sizing:inherit;'> (2020 National Analysis Dataset (October 2021, released October 2021)) [Internet database]. Retrieved from </span></span><a href='https://enviro.epa.gov/triexplorer/tri_release.chemical' style='color:rgb(110, 110, 110); box-sizing:inherit; font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;' target='_blank' rel='nofollow ugc noopener noreferrer'><span style='box-sizing:inherit; color:rgb(24, 33, 43);'><span style='box-sizing:inherit;'>https://enviro.epa.gov/triexplorer/</span></span></a><span style='box-sizing:inherit; font-family:&quot;Avenir Next&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color:rgb(24, 33, 43);'><span style='box-sizing:inherit;'>, (March 23, 2022)</span></span></font></span></p>",
    tags: ["Instant Apps", "Countdown", "Texas", "US", "Petroleum", "TRI-Program", "Toxic-Release", "Waste-Management"],
    snippet: "Explore the petroleum facilities of Texas, along with related information about waste management. ",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/391caae3232b48579cdaf3cf39fb3e8c/info/thumbnail/thumbnail1648130887192.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/countdown/index.html?appid=936a4570b8334fbeb906938af4c7420b",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 341,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Templates/Countdown",
      "/Categories/Industries/Oil and Gas"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678089600000
  },
  {
    id: "7ef0d8f001524ca7b6386d1adbe0c48f",
    owner: "App_Gal",
    created: 1657307169000,
    modified: 1657307509000,
    guid: null,
    name: null,
    title: "Wastewater Management in India",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<span style='font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px; background-color:rgb(255, 255, 255);'><font color='#000000'>Availability of safe and good water is increasingly becoming a challenge due to growing population and the degrading natural environment. Under such circumstances it is crucial that we create a circular and sustainable economy that would allow us to manage and treat wastewater. UN Water, an agency that works on &quot;water issues&quot; by informing policies, launching water-related campaigns, collecting and managing coherent and reliable data, reports that around 80% of the world's wastewater flows back into the ecosystem without being treated contributing to contaminated drinking water for approximately 1.8 billion people (UN WWDR, 2017).</font></span><div><span style='color:rgb(0, 0, 0); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><br /></span></div><div><span style='color:rgb(0, 0, 0); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'>For India, lack of resources for wastewater treatment is a crucial problem as it then leads to polluted freshwater resources for ~1.38 billion people. This Portfolio app puts together several resources that would allow local and state governments to analyze current situations and implement infrastructure plans or policy-based reforms.</span><p style='font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font color='#000000' style='background-color:rgb(255, 255, 255);'><br /><b><font size='2'>Data Source:</font></b></font></p><ul><li><font color='#000000' size='2' style='background-color:rgb(255, 255, 255);'>Ehalt Macedo, H., Lehner, B., Nicell, J. A., Grill, G., Li, J., Limtong, A., Shakya, R.: Distribution and characteristics of wastewater treatment plants within the global river network. Earth System Science Data. 2022.</font></li><li><font color='#000000' size='2' style='background-color:rgb(255, 255, 255);'>Central Pollution Control Board of India</font></li></ul></div>",
    tags: [
      "Instant-Apps",
      "Portfolio",
      "Accordian",
      "Wastewater",
      "Wastewater-Treatment",
      "Waste-Management",
      "Wastewater-Management",
      "India",
      "States",
      "SDG"
    ],
    snippet:
      "Explore different resources to analyze the current wastewater management conditions in different states of India.",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/7ef0d8f001524ca7b6386d1adbe0c48f/info/thumbnail/thumbnail1657307508589.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation:
      "Ehalt Macedo, H., Lehner, B., Nicell, J. A., Grill, G., Li, J., Limtong, A., Shakya, R.: Distribution and characteristics of wastewater treatment plants within the global river network. Earth System Science Data. 2022.",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/portfolio/index.html?appid=c1ee7150f18040c5b1752b36c7f40eea",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 242,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Public Works",
      "/Categories/Templates/Portfolio",
      "/Categories/Industries/Global and Regional"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678107600000
  },
  {
    id: "69cc67517e5f45609d7fe45061212795",
    owner: "App_Gal",
    created: 1659381358000,
    modified: 1659381454000,
    guid: null,
    name: null,
    title: "World's Population Density By Latitude",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>Population Density is the concentration of people in a specific area. It helps to quantify demography. The map used to create the app uses the Global Human Settlement Layer (GHSL) created by the European Commission. The map is visualized based on population density (persons per square mile) between latitudes at one degree intervals. A second layer that situates global cities based on population overlays the population density layer and allows the user to look at the cities that contributed to the population density in the latitude zones.</font></p><p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>Search for a location to learn more about the latitude zone it is located in and other global cities in the same zone. Use one of these search methods:</font></p><ul><li><font size='3' style='font-family:inherit;'>Click the search box and type in an address or choose <strong>Use current location</strong></font></li><li><font size='3' style='font-family:inherit;'>Click within the map</font></li><li><font size='3' style='font-family:inherit;'>Use the <strong>Draw a Zone</strong> tool to draw a polygon in the map</font></li></ul><p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='3' style='font-family:inherit;'>Results will include information about the latitude zone and other global cities. The results can be <strong>exported into a CSV</strong> or can be shared using the <strong>Screenshot</strong> tool. Use the <strong>Filter</strong> tool to filter the map by hemisphere and latitude zones!</font></p><p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><font size='2' style='font-family:inherit;'><b>Data Source:</b> <a href='https://ghsl.jrc.ec.europa.eu/index.php' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;' target='_blank' rel='nofollow ugc noopener noreferrer'>GHSL, European Commission</a></font></p>",
    tags: ["Instant-Apps", "Zone-Lookup", "Population", "Density", "World", "Latitudes", "Zones", "Population-Density"],
    snippet: "Explore the concept of population density (persons per square mile) by latitude zones!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/69cc67517e5f45609d7fe45061212795/info/thumbnail/thumbnail1659381453111.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/lookup/index.html?appid=f8c1caee57794b8da414572c30f74358",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 227,
    groupCategories: ["/Categories/Templates/Zone Lookup", "/Categories/Industries/Global and Regional"],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678100400000
  },
  {
    id: "e1ca339929a149ecaf588dd43587b66e",
    owner: "App_Gal",
    created: 1661190026000,
    modified: 1661190106000,
    guid: null,
    name: null,
    title: "Post-disaster Damage Assessment: Odisha, India",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='margin-top:0px; margin-bottom:1.5rem; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><font size='3' style='font-family:inherit;'>Coastal Odisha has faced several cyclonic events over the last two decades and is still recovering from the losses and impacts of the previous storms. The state's early warning systems and disaster preparedness have improved over the years because of which the loss of human life has reduced over the years. But its approach towards long-term recovery is still very limited.</font></p><p style='margin-top:0px; margin-bottom:1.5rem; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><font size='3' style='font-family:inherit;'>This app can be used to collect regional and neighborhood level information post-disaster to understand the varying scales of damages caused and to create a database that can be further analyzed for initiating discussions on long-term recovery processes for the coastal region of the state. The data collection method can include field assessments and secondary methods, like documenting media reports. The app currently visualizes data collected during a field assessment conducted along National Highway 316 from Pipili to Puri, approximately three weeks post-Cyclone Fani, that hit the eastern coast of India on May 3, 2019.</font></p><p style='margin-top:0px; margin-bottom:0px; font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'></p><ol><li><font size='3' style='font-family:inherit;'>Add and edit data by using the '<i>Edit'</i> tool. Damaged features have been categorized broadly into seven classes (as seen in the legend), which have been further subcategorized, for example, vegetation has been subcategorized as cropland and trees. While adding data to the app, choose the subcategory and fill in relevant information using the attribute data form. </font></li><li><font size='3' style='font-family:inherit;'>To add a data point, use the '<i>Search</i>' tool to search for a location or use the '<i>Find my Location</i>' tool. </font></li><li><font size='3' style='font-family:inherit;'>Use the '<i>Basemap Gallery</i>' to change the reference map while adding, updating, or viewing data.</font></li></ol>",
    tags: [
      "Instant-Apps",
      "Sidebar",
      "Edit-Tool",
      "Disaster-Management",
      "Disaster-preparedness",
      "Odisha",
      "India",
      "Cyclone",
      "Post-Disaster",
      "Field-Survey",
      "Long-term-Recovery"
    ],
    snippet:
      "Collect data post-disaster to create a database to initiate discussions on long-term recovery approaches!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/e1ca339929a149ecaf588dd43587b66e/info/thumbnail/thumbnail1661190104735.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: null,
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/sidebar/index.html?appid=f690f41050ed47b5a627919eca4f452e",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 210,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Global and Regional",
      "/Categories/Templates/Sidebar"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678071600000
  },
  {
    id: "c001c5b70b5844fabe3070737bd24804",
    owner: "App_Gal",
    created: 1657307679000,
    modified: 1657308020000,
    guid: null,
    name: null,
    title: "International Housing Affordability",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p><span style='background:white;'><font color='#000000'>Cost of housing\nis largely decided by the kind of place we live in! </font></span><span style='color:rgb(0, 0, 0);'>An annual report published by the Urban Reform Institute in\nTexas calculates an affordability score for several housing markets across the\nglobe based on median household income and median housing price. Any city with\na score above 5.1 is classified as unaffordable. Using the dataset published by\nthem this app visualizes and ranks the most and the least affordable housing\nmarkets of the world in the year 2022 and 2021.</span></p>\n\n<p><span style='background:white;'><font color='#000000'>Start exploring\nthe data by using the countdown sections to page through each location of this Countdown app. While\npaging through the locations in the countdown sections, the map will focus on\nthe extent that showcases that feature. Use the pin to compare feature to\nidentify relationships among the locations in the map.</font></span></p>",
    tags: ["Instant-Apps", "Countdown", "Housing", "Affordability", "Housing-Markets"],
    snippet: "Learn more about some of the most expensive housing markets of the world in the years 2021 and 2022!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/c001c5b70b5844fabe3070737bd24804/info/thumbnail/thumbnail1657308019606.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation:
      "Demographia International Housing Affordability, 2022 by the Urban Reform Institute and Frontier Centre for Public Policy",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/countdown/index.html?appid=573812ace75a438ea9d9613e36f1ca68",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 251,
    groupCategories: ["/Categories/Industries/Real Estate", "/Categories/Templates/Countdown"],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678064400000
  },
  {
    id: "9d8afb2877a04f259c8ec82441917b83",
    owner: "App_Gal",
    created: 1661190143000,
    modified: 1661190204000,
    guid: null,
    name: null,
    title: "Mapping the Slums of Cape Town",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><b><font size='3' style='font-family:inherit;'>Introduction:</font></b></span></span></p><p style='margin-top:0px; margin-bottom:1.5rem; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:14px;'><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial; font-size:10.5pt;'>As people are increasingly migrating to urban areas, rise of slums have become a common phenomenon in most cities and metropolitan areas of the world. Most urban planners have come to realize that slums are not an isolated phenomenon and getting rid of them wholly is unachievable. So instead of eliminating such settlements from the urban fabric, they now try to focus their research and practice on improving the conditions of these settlements, which include access to basic infrastructure and services, availability of affordable housing and employment and land tenure security. On the other hand, many city governments across the globe still refuse to acknowledge the existence of slums, with their attitudes ranging from eviction to reluctant acceptance and upgradation. The biggest and most imperative challenge in this regard has been identifying and mapping slums due to the lack of official records and information in most cases.</span></span></p><p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><b><font size='3' style='font-family:inherit;'>About the app:</font></b></span></span></p><p style='margin-top:0px; margin-bottom:1.5rem; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:14px;'><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial; font-size:10.5pt;'>This app provides an example of a data collection and mapping project that can evolve as a community participation project by involving citizens in the mapping of slums and urban services and amenities around them. The app and the geolocated information can be used to identify key issues and problems of the slum residents and help to design solutions for meeting their needs.</span></span></p><p style='margin-top:0px; margin-bottom:1.5rem; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:14px;'><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial; font-size:10.5pt;'>In 2018, 56.2% of the urban population (238 million) of Sub-Saharan Africa was living in slums (UN Stats, 2021). The app uses Cape Town in South Africa as an example, which is also home to one of the largest slums of the world, Khayelitsha. This app uses crowdsourced data from OpenStreetMap, and publicly available data published by the </span></span><a href='https://odp-cctegis.opendata.arcgis.com/' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>City of Cape Town</a><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial; font-size:10.5pt;'>.</span></span></p><p style='margin-top:0px; margin-bottom:1.5rem; font-size:16px; color:rgb(74, 74, 74); font-family:&quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif;'><span style='font-family:inherit; color:rgb(64, 64, 64);'><span style='font-family:Arial, sans-serif; background-image:initial; background-position:initial; background-size:initial; background-repeat:initial; background-attachment:initial; background-origin:initial; background-clip:initial;'><b><font size='3' style='font-family:inherit;'>How to use the app:</font></b></span></span></p><ol><li><font size='3' style='font-family:inherit;'>Add and edit slums to the map by using the '<i>Edit'</i> tool. Use the '<i>Snapping</i>' tool while adding or editing the slum boundaries.</font></li><li><font size='3' style='font-family:inherit;'><font style='font-family:inherit;'>Urban Services and Amenities have been broadly categorized into four groups - Community Services, Emergency Services, Health Services and Transportation Amenities. While adding data, choose the type of amenity, use the </font>'<i>Edit'</i> tool to add it to the map and fill in relevant information using the attribute data form.  </font></li><li><font size='3' style='font-family:inherit;'>To add a service or amenity, use the '<i>Search</i>' tool to search for a location or use the '<i>Find my Location</i>' tool. </font></li><li><font size='3' style='font-family:inherit;'>Use the '<i>Basemap Gallery</i>' to change the reference map while adding, updating, or viewing data.</font></li><li><font size='3' style='font-family:inherit;'>Use '<i>Layer List</i>' to enable or disable layers from the map.</font></li><li><font size='3' style='font-family:inherit;'>The slum layer in the Layer List comes with a '<i>Show Table</i>' option. Click on it to open and view the attribute table for the slums in Cape Town. </font></li></ol><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><font size='3' style='font-family:inherit;'><br /></font></div><div style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><font size='2' style='font-family:inherit;'><b>Data Source(s):</b> OpenStreetMap; <a href='https://odp-cctegis.opendata.arcgis.com/' style='color:rgb(0, 121, 193); text-decoration-line:none; font-family:inherit;' target='_blank' rel='nofollow ugc noopener noreferrer'>City of Cape Town Open Data Portal</a></font></div>",
    tags: [
      "Instant-Apps",
      "Sidebar",
      "Edit-Tool",
      "Cape-Town",
      "SubSaharan-Africa",
      "Slums",
      "Community",
      "Slum-Mapping",
      "Crowdsourced-Data"
    ],
    snippet: "A community participation project to aid data collection and mapping of slums and amenities around them!",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/9d8afb2877a04f259c8ec82441917b83/info/thumbnail/thumbnail1661190203481.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: "OpenStreetMap; City of Cape Town Open Data Portal",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/sidebar/index.html?appid=10a842052ae74fd6b4a15a63c9665443",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 202,
    groupCategories: [
      "/Categories/Industries/Public Policy and Planning",
      "/Categories/Industries/Global and Regional",
      "/Categories/Templates/Sidebar"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678114800000
  },
  {
    id: "da3a9825df97478bb91ff2537243a665",
    owner: "App_Gal",
    created: 1657310486000,
    modified: 1657310745000,
    guid: null,
    name: null,
    title: "Pollution in the Ganges",
    type: "Web Mapping Application",
    typeKeywords: ["Map", "Mapping Site", "Online Map", "Web Map"],
    description:
      "<span style='font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px; color:rgb(51, 51, 51);'>An assemblage of untreated urban sewage, animal waste, pesticides, fertilizers, and industrial metals makes the Ganges one of the most polluted rivers in the world. However, flowing through the four Indian states of Uttarakhand, Uttar Pradesh, Bihar and West Bengal, it is still the source of life for 30% of India's population (~ 400 million). </span><p style='color:rgb(74, 74, 74); font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><span style='color:rgb(51, 51, 51);'>This app visualizes the river's course and it's basin along with the cities and sources of pollution along it's banks.</span></p><p style='color:rgb(74, 74, 74); font-family:&quot;Avenir Next W01&quot;, &quot;Avenir Next W00&quot;, &quot;Avenir Next&quot;, Avenir, &quot;Helvetica Neue&quot;, sans-serif; font-size:16px;'><span style='background-color:rgb(255, 255, 255);'><span style='margin-top:0px; margin-right:revert; margin-bottom:0px; margin-left:revert; color:rgb(21, 21, 21); font-size:14px;'><b>Data Source:</b></span><span style='margin-top:0px; margin-right:revert; margin-bottom:0px; margin-left:revert; font-weight:revert; color:rgb(21, 21, 21); font-size:14px;'> </span><span style='color:rgb(21, 21, 21); font-size:14px;'>Central Pollution Control Board (CPCB)</span></span><span style='color:rgb(51, 51, 51);'><br /></span></p>",
    tags: ["Instant-Apps", "Exhibit", "Ganges", "India", "Pollution", "River-Course"],
    snippet:
      "Learn more about the course of River Ganges along with the cities and sources of pollution along it's banks.",
    thumbnail:
      "https://www.arcgis.com/sharing/rest/content/items/da3a9825df97478bb91ff2537243a665/info/thumbnail/thumbnail1657310744727.png",
    documentation: null,
    extent: [],
    categories: [],
    spatialReference: null,
    accessInformation: "Data Source: Central Pollution Control Board (CPCB)",
    licenseInfo: null,
    culture: "en-us",
    properties: null,
    advancedSettings: null,
    url: "https://webapps.maps.arcgis.com/apps/instant/exhibit/index.html?appid=20be7e569e0a4603bc0ca330e1b896f8",
    proxyFilter: null,
    access: "public",
    size: -1,
    subInfo: 0,
    appCategories: [],
    industries: [],
    languages: [],
    largeThumbnail: null,
    banner: null,
    screenshots: [],
    listed: false,
    numComments: 0,
    numRatings: 0,
    avgRating: 0,
    numViews: 246,
    groupCategories: [
      "/Categories/Templates/Exhibit",
      "/Categories/Industries/Public Works",
      "/Categories/Industries/Global and Regional",
      "/Categories/Industries/Environment and Natural Resources/Natural Resources"
    ],
    scoreCompleteness: 83,
    groupDesignations: null,
    lastViewed: 1678068000000
  }
];
